//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skillton.Test.Console_Net48.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EmployeeDB.sdf")]
        public string DatabaseFileName {
            get {
                return ((string)(this["DatabaseFileName"]));
            }
            set {
                this["DatabaseFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Skillton.Test.log")]
        public string LogFileName {
            get {
                return ((string)(this["LogFileName"]));
            }
            set {
                this["LogFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ValidatorFirstNameMinLength {
            get {
                return ((int)(this["ValidatorFirstNameMinLength"]));
            }
            set {
                this["ValidatorFirstNameMinLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int ValidatorLastNameMinLength {
            get {
                return ((int)(this["ValidatorLastNameMinLength"]));
            }
            set {
                this["ValidatorLastNameMinLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int ValidatorFirstNameMaxLength {
            get {
                return ((int)(this["ValidatorFirstNameMaxLength"]));
            }
            set {
                this["ValidatorFirstNameMaxLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int ValidatorLastNameMaxLength {
            get {
                return ((int)(this["ValidatorLastNameMaxLength"]));
            }
            set {
                this["ValidatorLastNameMaxLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1900-01-01")]
        public global::System.DateTime ValidatorDateOfBirthMinValue {
            get {
                return ((global::System.DateTime)(this["ValidatorDateOfBirthMinValue"]));
            }
            set {
                this["ValidatorDateOfBirthMinValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2020-01-01")]
        public global::System.DateTime ValidatorDateOfBirthMaxValue {
            get {
                return ((global::System.DateTime)(this["ValidatorDateOfBirthMaxValue"]));
            }
            set {
                this["ValidatorDateOfBirthMaxValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("^[a-zA-Zа-яА-ЯёЁ]+(?:[ -\'][a-zA-Zа-яА-ЯёЁ]+)*$")]
        public string ValidatorNameValueValidationMask {
            get {
                return ((string)(this["ValidatorNameValueValidationMask"]));
            }
            set {
                this["ValidatorNameValueValidationMask"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("^(?(\"\")(\"\"[^\"\"]+?\"\"@)|(([0-9a-z]((\\.(?!\\.))|[-!#\\$%&\'\\*\\+/=\\?\\^`\\{\\}\\|~\\w])*)(?<=" +
            "[0-9a-z])@))(?(\\[)(\\[(\\d{1,3}\\.){3}\\d{1,3}\\])|(([0-9a-z][-\\w]*[0-9a-z]*\\.)+[a-z0" +
            "-9]{2,17}))$")]
        public string ValidatorEmailValueValidationMask {
            get {
                return ((string)(this["ValidatorEmailValueValidationMask"]));
            }
            set {
                this["ValidatorEmailValueValidationMask"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal ValidatorSalaryMinValue {
            get {
                return ((decimal)(this["ValidatorSalaryMinValue"]));
            }
            set {
                this["ValidatorSalaryMinValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("999999")]
        public decimal ValidatorSalaryMaxValue {
            get {
                return ((decimal)(this["ValidatorSalaryMaxValue"]));
            }
            set {
                this["ValidatorSalaryMaxValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VpbrFu6sZbAXhYPk7tcQ3Q==")]
        public string DatabasePassword {
            get {
                return ((string)(this["DatabasePassword"]));
            }
            set {
                this["DatabasePassword"] = value;
            }
        }
    }
}
